[renderer]
backend= "vulkan"

[colors.primary]
background = "0x1A1A1A"
foreground = "0xFFFFFF"

[font.normal]
family = "Liberation Mono"
style = "Regular"

[font.bold]
family = "Liberation Mono"
style = "Medium"

[font.italic]
family = "Liberation Mono"
style = "Light Italic"

[font]
size = 14.0
